/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          50:  'var(--il-primary-50)',
          100: 'var(--il-primary-100)',
          200: 'var(--il-primary-200)',
          300: 'var(--il-primary-300)',
          400: 'var(--il-primary-400)',
          500: 'var(--il-primary-500)',
          600: 'var(--il-primary-600)',
          700: 'var(--il-primary-700)',
        },
        success: {
          50:  'var(--il-success-50)',
          400: 'var(--il-success-400)',
          500: 'var(--il-success-500)',
          600: 'var(--il-success-600)',
        },
        warning: {
          50:  'var(--il-warning-50)',
          400: 'var(--il-warning-400)',
          500: 'var(--il-warning-500)',
          600: 'var(--il-warning-600)',
        },
        danger: {
          50:  'var(--il-danger-50)',
          400: 'var(--il-danger-400)',
          500: 'var(--il-danger-500)',
          600: 'var(--il-danger-600)',
        },
        info: {
          50:  'var(--il-info-50)',
          400: 'var(--il-info-400)',
          500: 'var(--il-info-500)',
          600: 'var(--il-info-600)',
        },
        bg:         'var(--il-bg)',
        'bg-subtle':'var(--il-bg-subtle)',
        surface:    { DEFAULT: 'var(--il-surface-1)', '0': 'var(--il-surface-0)', '1': 'var(--il-surface-1)', '2': 'var(--il-surface-2)', '3': 'var(--il-surface-3)' },
        border:     { DEFAULT: 'var(--il-border)', strong: 'var(--il-border-strong)' },
        text:       { DEFAULT: 'var(--il-text)', secondary: 'var(--il-text-secondary)', muted: 'var(--il-text-muted)', inverse: 'var(--il-text-inverse)' },
        neutral: {
          50:  'var(--il-surface-0)',
          100: 'var(--il-surface-1)',
          200: 'var(--il-surface-2)',
          300: 'var(--il-surface-3)',
          400: 'var(--il-text-secondary)',
          500: 'var(--il-text-muted)',
          800: 'var(--il-text)',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      fontSize: {
        xs:   'var(--il-font-xs)',
        sm:   'var(--il-font-sm)',
        base: 'var(--il-font-base)',
        lg:   'var(--il-font-lg)',
        xl:   'var(--il-font-xl)',
        '2xl': 'var(--il-font-2xl)',
        '3xl': 'var(--il-font-3xl)',
        '4xl': 'var(--il-font-4xl)',
        '5xl': 'var(--il-font-5xl)',
      },
      spacing: {
        '0':   'var(--il-space-0)',
        '1':   'var(--il-space-1)',
        '2':   'var(--il-space-2)',
        '3':   'var(--il-space-3)',
        '4':   'var(--il-space-4)',
        '5':   'var(--il-space-5)',
        '6':   'var(--il-space-6)',
        '8':   'var(--il-space-8)',
        '10':  'var(--il-space-10)',
        '12':  'var(--il-space-12)',
        '16':  'var(--il-space-16)',
      },
      borderRadius: {
        sm:    'var(--il-radius-sm)',
        md:    'var(--il-radius-md)',
        lg:    'var(--il-radius-lg)',
        xl:    'var(--il-radius-xl)',
        '2xl': 'var(--il-radius-2xl)',
        full:  'var(--il-radius-full)',
      },
      boxShadow: {
        sm:    'var(--il-shadow-sm)',
        md:    'var(--il-shadow-md)',
        lg:    'var(--il-shadow-lg)',
        xl:    'var(--il-shadow-xl)',
        ring:  'var(--il-shadow-ring)',
      },
      transitionDuration: {
        fast: '100ms',
        normal: '200ms',
        slow: '300ms',
      },
      transitionTimingFunction: {
        'ease-in':     'cubic-bezier(0.4, 0, 1, 1)',
        'ease-out':    'cubic-bezier(0, 0, 0.2, 1)',
        'ease-in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      keyframes: {
        'fade-in': {
          '0%':   { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'skeleton-shimmer': {
          '0%':   { backgroundPosition: '-200px 0' },
          '100%': { backgroundPosition: 'calc(200px + 100%) 0' },
        },
        'recording-dot': {
          '0%, 100%': { opacity: '1', transform: 'scale(1)' },
          '50%':      { opacity: '0.5', transform: 'scale(1.1)' },
        },
        'spin': {
          '0%':   { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
      },
      animation: {
        'fade-in':            'fade-in 200ms ease-out',
        'skeleton-shimmer':   'skeleton-shimmer 1.5s ease-in-out infinite',
        'recording-dot':      'recording-dot 1s ease-in-out infinite',
        'spin':               'spin 0.8s linear infinite',
      },
      zIndex: {
        'dropdown': 'var(--il-z-dropdown)',
        'sticky':   'var(--il-z-sticky)',
        'fixed':    'var(--il-z-fixed)',
        'overlay':  'var(--il-z-overlay)',
        'modal':    'var(--il-z-modal)',
        'toast':    'var(--il-z-toast)',
      },
    },
  },
  plugins: [],
}
